# Generated by Django 2.2 on 2021-08-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User Information', 'verbose_name_plural': 'User Information'},
        ),
    ]
